/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'finalPrice' : bigint,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'customer' : Principal,
  'quoteId' : string,
  'serviceProvider' : Principal,
  'advanceAmount' : bigint,
  'paymentId' : string,
  'timestamp' : Time,
  'advancePercentage' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'pendingPayment' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export type DeliveryType = { 'appliance' : null } |
  { 'smallPackage' : null } |
  { 'furniture' : null } |
  { 'mediumPackage' : null } |
  { 'largePackage' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface InstantQuoteRequest {
  'vehicleType' : string,
  'dropOffLocation' : string,
  'addOnServices' : Array<string>,
  'advanceAmount' : bigint,
  'schedule' : string,
  'totalPrice' : bigint,
  'priceBreakdown' : PriceBreakdown,
  'moveType' : MoveType,
  'pickupLocation' : string,
  'advancePercentage' : bigint,
}
export interface Location {
  'latitude' : number,
  'longitude' : number,
  'address' : string,
}
export type MoveType = { 'rk' : null } |
  { 'bhk' : { 'size' : string } } |
  { 'office' : null };
export type PaymentStatus = { 'cancelled' : null } |
  { 'driverAssigned' : null } |
  { 'completed' : null } |
  { 'pendingPayment' : null } |
  { 'confirmed' : null };
export interface PriceBreakdown {
  'finalPrice' : bigint,
  'vehicleType' : bigint,
  'goodsType' : bigint,
  'distance' : bigint,
  'addOns' : bigint,
  'bulkDiscount' : bigint,
  'timeSlot' : bigint,
  'baseFare' : bigint,
}
export type Principal = Principal;
export interface Quote {
  'id' : string,
  'weightRange' : WeightRange,
  'dropOffLocation' : Location,
  'customer' : Principal,
  'estimatedPrice' : bigint,
  'deliveryType' : DeliveryType,
  'distance' : bigint,
  'advanceAmount' : bigint,
  'timestamp' : Time,
  'pickupLocation' : Location,
  'advancePercentage' : bigint,
}
export interface RazorpayOrder {
  'bookingId' : string,
  'receipt' : string,
  'orderId' : string,
  'currency' : string,
  'notes' : string,
  'amount' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface ServiceProviderProfile {
  'id' : Principal,
  'contactInfo' : string,
  'name' : string,
  'availability' : boolean,
  'servicesOffered' : Array<DeliveryType>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'userType' : { 'customer' : null } |
    { 'serviceProvider' : null },
  'contactInfo' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightRange {
  'maxWeight' : number,
  'rangeLabel' : string,
  'unit' : string,
  'minWeight' : number,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__bookings' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Booking]>
  >,
  '__instantQuoteOwners' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Principal]>
  >,
  '__instantQuotes' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, InstantQuoteRequest]>
  >,
  '__quotes' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, Quote]>
  >,
  '__razorpayOrders' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, RazorpayOrder]>
  >,
  '__serviceProviderProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, ServiceProviderProfile]>
  >,
  '__stripeConfiguration' : ActorMethod<[], [] | [StripeConfiguration]>,
  '__userProfiles' : ActorMethod<
    [[] | [Principal], [] | [bigint]],
    Array<[Principal, UserProfile]>
  >,
  '__weightRanges' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, WeightRange]>
  >,
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'autoCancelPendingBookings' : ActorMethod<[], Array<string>>,
  'createBooking' : ActorMethod<[string, Principal], Booking>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInstantQuoteRequest' : ActorMethod<
    [string, string, MoveType, string, Array<string>, string, bigint],
    InstantQuoteRequest
  >,
  'createRazorpayOrder' : ActorMethod<[string], RazorpayOrder>,
  'createServiceProviderProfile' : ActorMethod<
    [ServiceProviderProfile],
    undefined
  >,
  'createWeightRange' : ActorMethod<
    [string, number, number, string],
    undefined
  >,
  'generateBalancePaymentLink' : ActorMethod<[string], string>,
  'geocodeAddress' : ActorMethod<[string], string>,
  'getAllDeliveryTypes' : ActorMethod<[], Array<DeliveryType>>,
  'getAllInstantQuoteRequests' : ActorMethod<[], Array<InstantQuoteRequest>>,
  'getAllWeightRanges' : ActorMethod<[], Array<WeightRange>>,
  'getBookingById' : ActorMethod<[string], Booking>,
  'getBookingsByCustomer' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyInstantQuoteRequests' : ActorMethod<[], Array<InstantQuoteRequest>>,
  'getMyQuotes' : ActorMethod<[], Array<Quote>>,
  'getQuote' : ActorMethod<
    [Location, Location, DeliveryType, WeightRange, bigint],
    Quote
  >,
  'getQuotesByDeliveryType' : ActorMethod<[DeliveryType], Array<Quote>>,
  'getQuotesByDeliveryTypeAndWeightRange' : ActorMethod<
    [DeliveryType, string],
    Array<Quote>
  >,
  'getQuotesByWeightRange' : ActorMethod<[string], Array<Quote>>,
  'getRouteDistance' : ActorMethod<[number, number, number, number], bigint>,
  'getServiceProviderProfile' : ActorMethod<
    [Principal],
    [] | [ServiceProviderProfile]
  >,
  'getServiceProviderProfiles' : ActorMethod<[], Array<ServiceProviderProfile>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightRange' : ActorMethod<[string], [] | [WeightRange]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingPayment' : ActorMethod<
    [string, string, PaymentStatus],
    undefined
  >,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[string, PaymentStatus], undefined>,
  'updateServiceProviderProfile' : ActorMethod<
    [ServiceProviderProfile],
    undefined
  >,
  'verifyRazorpayPayment' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];