/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'pendingPayment' : IDL.Null,
  'confirmed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'driverAssigned' : IDL.Null,
  'completed' : IDL.Null,
  'pendingPayment' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Principal = IDL.Principal;
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'finalPrice' : IDL.Int,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'customer' : Principal,
  'quoteId' : IDL.Text,
  'serviceProvider' : Principal,
  'advanceAmount' : IDL.Int,
  'paymentId' : IDL.Text,
  'timestamp' : Time,
  'advancePercentage' : IDL.Int,
});
export const PriceBreakdown = IDL.Record({
  'finalPrice' : IDL.Int,
  'vehicleType' : IDL.Int,
  'goodsType' : IDL.Int,
  'distance' : IDL.Int,
  'addOns' : IDL.Int,
  'bulkDiscount' : IDL.Int,
  'timeSlot' : IDL.Int,
  'baseFare' : IDL.Int,
});
export const MoveType = IDL.Variant({
  'rk' : IDL.Null,
  'bhk' : IDL.Record({ 'size' : IDL.Text }),
  'office' : IDL.Null,
});
export const InstantQuoteRequest = IDL.Record({
  'vehicleType' : IDL.Text,
  'dropOffLocation' : IDL.Text,
  'addOnServices' : IDL.Vec(IDL.Text),
  'advanceAmount' : IDL.Int,
  'schedule' : IDL.Text,
  'totalPrice' : IDL.Int,
  'priceBreakdown' : PriceBreakdown,
  'moveType' : MoveType,
  'pickupLocation' : IDL.Text,
  'advancePercentage' : IDL.Int,
});
export const WeightRange = IDL.Record({
  'maxWeight' : IDL.Float64,
  'rangeLabel' : IDL.Text,
  'unit' : IDL.Text,
  'minWeight' : IDL.Float64,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
});
export const DeliveryType = IDL.Variant({
  'appliance' : IDL.Null,
  'smallPackage' : IDL.Null,
  'furniture' : IDL.Null,
  'mediumPackage' : IDL.Null,
  'largePackage' : IDL.Null,
});
export const Quote = IDL.Record({
  'id' : IDL.Text,
  'weightRange' : WeightRange,
  'dropOffLocation' : Location,
  'customer' : Principal,
  'estimatedPrice' : IDL.Int,
  'deliveryType' : DeliveryType,
  'distance' : IDL.Int,
  'advanceAmount' : IDL.Int,
  'timestamp' : Time,
  'pickupLocation' : Location,
  'advancePercentage' : IDL.Int,
});
export const RazorpayOrder = IDL.Record({
  'bookingId' : IDL.Text,
  'receipt' : IDL.Text,
  'orderId' : IDL.Text,
  'currency' : IDL.Text,
  'notes' : IDL.Text,
  'amount' : IDL.Int,
});
export const ServiceProviderProfile = IDL.Record({
  'id' : Principal,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'availability' : IDL.Bool,
  'servicesOffered' : IDL.Vec(DeliveryType),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({
    'customer' : IDL.Null,
    'serviceProvider' : IDL.Null,
  }),
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__bookings' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, Booking))],
      ['query'],
    ),
  '__instantQuoteOwners' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, Principal))],
      ['query'],
    ),
  '__instantQuotes' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, InstantQuoteRequest))],
      ['query'],
    ),
  '__quotes' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, Quote))],
      ['query'],
    ),
  '__razorpayOrders' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, RazorpayOrder))],
      ['query'],
    ),
  '__serviceProviderProfiles' : IDL.Func(
      [IDL.Opt(Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(Principal, ServiceProviderProfile))],
      ['query'],
    ),
  '__stripeConfiguration' : IDL.Func(
      [],
      [IDL.Opt(StripeConfiguration)],
      ['query'],
    ),
  '__userProfiles' : IDL.Func(
      [IDL.Opt(Principal), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(Principal, UserProfile))],
      ['query'],
    ),
  '__weightRanges' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, WeightRange))],
      ['query'],
    ),
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'autoCancelPendingBookings' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'createBooking' : IDL.Func([IDL.Text, Principal], [Booking], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInstantQuoteRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        MoveType,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Int,
      ],
      [InstantQuoteRequest],
      [],
    ),
  'createRazorpayOrder' : IDL.Func([IDL.Text], [RazorpayOrder], []),
  'createServiceProviderProfile' : IDL.Func([ServiceProviderProfile], [], []),
  'createWeightRange' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'generateBalancePaymentLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'geocodeAddress' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllDeliveryTypes' : IDL.Func([], [IDL.Vec(DeliveryType)], ['query']),
  'getAllInstantQuoteRequests' : IDL.Func(
      [],
      [IDL.Vec(InstantQuoteRequest)],
      ['query'],
    ),
  'getAllWeightRanges' : IDL.Func([], [IDL.Vec(WeightRange)], ['query']),
  'getBookingById' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getBookingsByCustomer' : IDL.Func(
      [Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyInstantQuoteRequests' : IDL.Func(
      [],
      [IDL.Vec(InstantQuoteRequest)],
      ['query'],
    ),
  'getMyQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'getQuote' : IDL.Func(
      [Location, Location, DeliveryType, WeightRange, IDL.Int],
      [Quote],
      [],
    ),
  'getQuotesByDeliveryType' : IDL.Func(
      [DeliveryType],
      [IDL.Vec(Quote)],
      ['query'],
    ),
  'getQuotesByDeliveryTypeAndWeightRange' : IDL.Func(
      [DeliveryType, IDL.Text],
      [IDL.Vec(Quote)],
      ['query'],
    ),
  'getQuotesByWeightRange' : IDL.Func([IDL.Text], [IDL.Vec(Quote)], ['query']),
  'getRouteDistance' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Int],
      [],
    ),
  'getServiceProviderProfile' : IDL.Func(
      [Principal],
      [IDL.Opt(ServiceProviderProfile)],
      ['query'],
    ),
  'getServiceProviderProfiles' : IDL.Func(
      [],
      [IDL.Vec(ServiceProviderProfile)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'getWeightRange' : IDL.Func([IDL.Text], [IDL.Opt(WeightRange)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingPayment' : IDL.Func(
      [IDL.Text, IDL.Text, PaymentStatus],
      [],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  'updateServiceProviderProfile' : IDL.Func([ServiceProviderProfile], [], []),
  'verifyRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'pendingPayment' : IDL.Null,
    'confirmed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'driverAssigned' : IDL.Null,
    'completed' : IDL.Null,
    'pendingPayment' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Principal = IDL.Principal;
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'finalPrice' : IDL.Int,
    'status' : BookingStatus,
    'paymentStatus' : PaymentStatus,
    'customer' : Principal,
    'quoteId' : IDL.Text,
    'serviceProvider' : Principal,
    'advanceAmount' : IDL.Int,
    'paymentId' : IDL.Text,
    'timestamp' : Time,
    'advancePercentage' : IDL.Int,
  });
  const PriceBreakdown = IDL.Record({
    'finalPrice' : IDL.Int,
    'vehicleType' : IDL.Int,
    'goodsType' : IDL.Int,
    'distance' : IDL.Int,
    'addOns' : IDL.Int,
    'bulkDiscount' : IDL.Int,
    'timeSlot' : IDL.Int,
    'baseFare' : IDL.Int,
  });
  const MoveType = IDL.Variant({
    'rk' : IDL.Null,
    'bhk' : IDL.Record({ 'size' : IDL.Text }),
    'office' : IDL.Null,
  });
  const InstantQuoteRequest = IDL.Record({
    'vehicleType' : IDL.Text,
    'dropOffLocation' : IDL.Text,
    'addOnServices' : IDL.Vec(IDL.Text),
    'advanceAmount' : IDL.Int,
    'schedule' : IDL.Text,
    'totalPrice' : IDL.Int,
    'priceBreakdown' : PriceBreakdown,
    'moveType' : MoveType,
    'pickupLocation' : IDL.Text,
    'advancePercentage' : IDL.Int,
  });
  const WeightRange = IDL.Record({
    'maxWeight' : IDL.Float64,
    'rangeLabel' : IDL.Text,
    'unit' : IDL.Text,
    'minWeight' : IDL.Float64,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
  });
  const DeliveryType = IDL.Variant({
    'appliance' : IDL.Null,
    'smallPackage' : IDL.Null,
    'furniture' : IDL.Null,
    'mediumPackage' : IDL.Null,
    'largePackage' : IDL.Null,
  });
  const Quote = IDL.Record({
    'id' : IDL.Text,
    'weightRange' : WeightRange,
    'dropOffLocation' : Location,
    'customer' : Principal,
    'estimatedPrice' : IDL.Int,
    'deliveryType' : DeliveryType,
    'distance' : IDL.Int,
    'advanceAmount' : IDL.Int,
    'timestamp' : Time,
    'pickupLocation' : Location,
    'advancePercentage' : IDL.Int,
  });
  const RazorpayOrder = IDL.Record({
    'bookingId' : IDL.Text,
    'receipt' : IDL.Text,
    'orderId' : IDL.Text,
    'currency' : IDL.Text,
    'notes' : IDL.Text,
    'amount' : IDL.Int,
  });
  const ServiceProviderProfile = IDL.Record({
    'id' : Principal,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'availability' : IDL.Bool,
    'servicesOffered' : IDL.Vec(DeliveryType),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({
      'customer' : IDL.Null,
      'serviceProvider' : IDL.Null,
    }),
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__bookings' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, Booking))],
        ['query'],
      ),
    '__instantQuoteOwners' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, Principal))],
        ['query'],
      ),
    '__instantQuotes' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, InstantQuoteRequest))],
        ['query'],
      ),
    '__quotes' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, Quote))],
        ['query'],
      ),
    '__razorpayOrders' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, RazorpayOrder))],
        ['query'],
      ),
    '__serviceProviderProfiles' : IDL.Func(
        [IDL.Opt(Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(Principal, ServiceProviderProfile))],
        ['query'],
      ),
    '__stripeConfiguration' : IDL.Func(
        [],
        [IDL.Opt(StripeConfiguration)],
        ['query'],
      ),
    '__userProfiles' : IDL.Func(
        [IDL.Opt(Principal), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(Principal, UserProfile))],
        ['query'],
      ),
    '__weightRanges' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, WeightRange))],
        ['query'],
      ),
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'autoCancelPendingBookings' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'createBooking' : IDL.Func([IDL.Text, Principal], [Booking], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInstantQuoteRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          MoveType,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Int,
        ],
        [InstantQuoteRequest],
        [],
      ),
    'createRazorpayOrder' : IDL.Func([IDL.Text], [RazorpayOrder], []),
    'createServiceProviderProfile' : IDL.Func([ServiceProviderProfile], [], []),
    'createWeightRange' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'generateBalancePaymentLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'geocodeAddress' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllDeliveryTypes' : IDL.Func([], [IDL.Vec(DeliveryType)], ['query']),
    'getAllInstantQuoteRequests' : IDL.Func(
        [],
        [IDL.Vec(InstantQuoteRequest)],
        ['query'],
      ),
    'getAllWeightRanges' : IDL.Func([], [IDL.Vec(WeightRange)], ['query']),
    'getBookingById' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getBookingsByCustomer' : IDL.Func(
        [Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyInstantQuoteRequests' : IDL.Func(
        [],
        [IDL.Vec(InstantQuoteRequest)],
        ['query'],
      ),
    'getMyQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'getQuote' : IDL.Func(
        [Location, Location, DeliveryType, WeightRange, IDL.Int],
        [Quote],
        [],
      ),
    'getQuotesByDeliveryType' : IDL.Func(
        [DeliveryType],
        [IDL.Vec(Quote)],
        ['query'],
      ),
    'getQuotesByDeliveryTypeAndWeightRange' : IDL.Func(
        [DeliveryType, IDL.Text],
        [IDL.Vec(Quote)],
        ['query'],
      ),
    'getQuotesByWeightRange' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Quote)],
        ['query'],
      ),
    'getRouteDistance' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Int],
        [],
      ),
    'getServiceProviderProfile' : IDL.Func(
        [Principal],
        [IDL.Opt(ServiceProviderProfile)],
        ['query'],
      ),
    'getServiceProviderProfiles' : IDL.Func(
        [],
        [IDL.Vec(ServiceProviderProfile)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'getWeightRange' : IDL.Func([IDL.Text], [IDL.Opt(WeightRange)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingPayment' : IDL.Func(
        [IDL.Text, IDL.Text, PaymentStatus],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
    'updateServiceProviderProfile' : IDL.Func([ServiceProviderProfile], [], []),
    'verifyRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };