/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WeightRange {
    maxWeight: number;
    rangeLabel: string;
    unit: string;
    minWeight: number;
}
export interface Location {
    latitude: number;
    longitude: number;
    address: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export type MoveType = {
    __kind__: "rk";
    rk: null;
} | {
    __kind__: "bhk";
    bhk: {
        size: string;
    };
} | {
    __kind__: "office";
    office: null;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface InstantQuoteRequest {
    vehicleType: string;
    dropOffLocation: string;
    addOnServices: Array<string>;
    advanceAmount: bigint;
    schedule: string;
    totalPrice: bigint;
    priceBreakdown: PriceBreakdown;
    moveType: MoveType;
    pickupLocation: string;
    advancePercentage: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PriceBreakdown {
    finalPrice: bigint;
    vehicleType: bigint;
    goodsType: bigint;
    distance: bigint;
    addOns: bigint;
    bulkDiscount: bigint;
    timeSlot: bigint;
    baseFare: bigint;
}
export interface Booking {
    id: string;
    finalPrice: bigint;
    status: BookingStatus;
    paymentStatus: PaymentStatus;
    customer: Principal;
    quoteId: string;
    serviceProvider: Principal;
    advanceAmount: bigint;
    paymentId: string;
    timestamp: Time;
    advancePercentage: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface RazorpayOrder {
    bookingId: string;
    receipt: string;
    orderId: string;
    currency: string;
    notes: string;
    amount: bigint;
}
export interface Quote {
    id: string;
    weightRange: WeightRange;
    dropOffLocation: Location;
    customer: Principal;
    estimatedPrice: bigint;
    deliveryType: DeliveryType;
    distance: bigint;
    advanceAmount: bigint;
    timestamp: Time;
    pickupLocation: Location;
    advancePercentage: bigint;
}
export interface ServiceProviderProfile {
    id: Principal;
    contactInfo: string;
    name: string;
    availability: boolean;
    servicesOffered: Array<DeliveryType>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Principal = Principal;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface UserProfile {
    userType: Variant_customer_serviceProvider;
    contactInfo: string;
    name: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    pendingPayment = "pendingPayment",
    confirmed = "confirmed",
    inProgress = "inProgress"
}
export enum DeliveryType {
    appliance = "appliance",
    smallPackage = "smallPackage",
    furniture = "furniture",
    mediumPackage = "mediumPackage",
    largePackage = "largePackage"
}
export enum PaymentStatus {
    cancelled = "cancelled",
    driverAssigned = "driverAssigned",
    completed = "completed",
    pendingPayment = "pendingPayment",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_customer_serviceProvider {
    customer = "customer",
    serviceProvider = "serviceProvider"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __bookings(ko: string | null, count: bigint | null): Promise<Array<[string, Booking]>>;
    __instantQuoteOwners(ko: string | null, count: bigint | null): Promise<Array<[string, Principal]>>;
    __instantQuotes(ko: string | null, count: bigint | null): Promise<Array<[string, InstantQuoteRequest]>>;
    __quotes(ko: string | null, count: bigint | null): Promise<Array<[string, Quote]>>;
    __razorpayOrders(ko: string | null, count: bigint | null): Promise<Array<[string, RazorpayOrder]>>;
    __serviceProviderProfiles(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, ServiceProviderProfile]>>;
    __stripeConfiguration(): Promise<StripeConfiguration | null>;
    __userProfiles(ko: Principal | null, count: bigint | null): Promise<Array<[Principal, UserProfile]>>;
    __weightRanges(ko: string | null, count: bigint | null): Promise<Array<[string, WeightRange]>>;
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    autoCancelPendingBookings(): Promise<Array<string>>;
    createBooking(quoteId: string, serviceProvider: Principal): Promise<Booking>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createInstantQuoteRequest(pickupLocation: string, dropOffLocation: string, moveType: MoveType, vehicleType: string, addOnServices: Array<string>, schedule: string, advancePercentage: bigint): Promise<InstantQuoteRequest>;
    createRazorpayOrder(bookingId: string): Promise<RazorpayOrder>;
    createServiceProviderProfile(profile: ServiceProviderProfile): Promise<void>;
    createWeightRange(rangeLabel: string, minWeight: number, maxWeight: number, unit: string): Promise<void>;
    generateBalancePaymentLink(bookingId: string): Promise<string>;
    geocodeAddress(address: string): Promise<string>;
    getAllDeliveryTypes(): Promise<Array<DeliveryType>>;
    getAllInstantQuoteRequests(): Promise<Array<InstantQuoteRequest>>;
    getAllWeightRanges(): Promise<Array<WeightRange>>;
    getBookingById(bookingId: string): Promise<Booking>;
    getBookingsByCustomer(customer: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyInstantQuoteRequests(): Promise<Array<InstantQuoteRequest>>;
    getMyQuotes(): Promise<Array<Quote>>;
    getQuote(pickup: Location, dropOff: Location, deliveryType: DeliveryType, weightRange: WeightRange, advancePercentage: bigint): Promise<Quote>;
    getQuotesByDeliveryType(deliveryType: DeliveryType): Promise<Array<Quote>>;
    getQuotesByDeliveryTypeAndWeightRange(deliveryType: DeliveryType, weightRangeLabel: string): Promise<Array<Quote>>;
    getQuotesByWeightRange(weightRangeLabel: string): Promise<Array<Quote>>;
    getRouteDistance(startLat: number, startLng: number, endLat: number, endLng: number): Promise<bigint>;
    getServiceProviderProfile(providerId: Principal): Promise<ServiceProviderProfile | null>;
    getServiceProviderProfiles(): Promise<Array<ServiceProviderProfile>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightRange(rangeLabel: string): Promise<WeightRange | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBookingPayment(bookingId: string, paymentId: string, newPaymentStatus: PaymentStatus): Promise<void>;
    updateBookingStatus(bookingId: string, newStatus: BookingStatus): Promise<void>;
    updatePaymentStatus(bookingId: string, newStatus: PaymentStatus): Promise<void>;
    updateServiceProviderProfile(profile: ServiceProviderProfile): Promise<void>;
    verifyRazorpayPayment(bookingId: string, paymentId: string, orderId: string, signature: string): Promise<boolean>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, DeliveryType as _DeliveryType, Error as _Error, InstantQuoteRequest as _InstantQuoteRequest, Location as _Location, MoveType as _MoveType, PaymentStatus as _PaymentStatus, PriceBreakdown as _PriceBreakdown, Principal as _Principal, Quote as _Quote, Result as _Result, ServiceProviderProfile as _ServiceProviderProfile, StripeConfiguration as _StripeConfiguration, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WeightRange as _WeightRange, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __bookings(arg0: string | null, arg1: bigint | null): Promise<Array<[string, Booking]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__bookings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__bookings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __instantQuoteOwners(arg0: string | null, arg1: bigint | null): Promise<Array<[string, Principal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__instantQuoteOwners(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__instantQuoteOwners(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __instantQuotes(arg0: string | null, arg1: bigint | null): Promise<Array<[string, InstantQuoteRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__instantQuotes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__instantQuotes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async __quotes(arg0: string | null, arg1: bigint | null): Promise<Array<[string, Quote]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__quotes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__quotes(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async __razorpayOrders(arg0: string | null, arg1: bigint | null): Promise<Array<[string, RazorpayOrder]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__razorpayOrders(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__razorpayOrders(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __serviceProviderProfiles(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, ServiceProviderProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__serviceProviderProfiles(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__serviceProviderProfiles(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async __stripeConfiguration(): Promise<StripeConfiguration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.__stripeConfiguration();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__stripeConfiguration();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async __userProfiles(arg0: Principal | null, arg1: bigint | null): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__userProfiles(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userProfiles(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async __weightRanges(arg0: string | null, arg1: bigint | null): Promise<Array<[string, WeightRange]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__weightRanges(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__weightRanges(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async autoCancelPendingBookings(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.autoCancelPendingBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.autoCancelPendingBookings();
            return result;
        }
    }
    async createBooking(arg0: string, arg1: Principal): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1);
                return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1);
            return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createInstantQuoteRequest(arg0: string, arg1: string, arg2: MoveType, arg3: string, arg4: Array<string>, arg5: string, arg6: bigint): Promise<InstantQuoteRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createInstantQuoteRequest(arg0, arg1, to_candid_MoveType_n48(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return from_candid_InstantQuoteRequest_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInstantQuoteRequest(arg0, arg1, to_candid_MoveType_n48(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return from_candid_InstantQuoteRequest_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRazorpayOrder(arg0: string): Promise<RazorpayOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder(arg0);
            return result;
        }
    }
    async createServiceProviderProfile(arg0: ServiceProviderProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createServiceProviderProfile(to_candid_ServiceProviderProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServiceProviderProfile(to_candid_ServiceProviderProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createWeightRange(arg0: string, arg1: number, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWeightRange(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWeightRange(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async generateBalancePaymentLink(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateBalancePaymentLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateBalancePaymentLink(arg0);
            return result;
        }
    }
    async geocodeAddress(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.geocodeAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.geocodeAddress(arg0);
            return result;
        }
    }
    async getAllDeliveryTypes(): Promise<Array<DeliveryType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryTypes();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryTypes();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInstantQuoteRequests(): Promise<Array<InstantQuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstantQuoteRequests();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstantQuoteRequests();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWeightRanges(): Promise<Array<WeightRange>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWeightRanges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWeightRanges();
            return result;
        }
    }
    async getBookingById(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByCustomer(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByCustomer(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByCustomer(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInstantQuoteRequests(): Promise<Array<InstantQuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInstantQuoteRequests();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInstantQuoteRequests();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuotes();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuotes();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuote(arg0: Location, arg1: Location, arg2: DeliveryType, arg3: WeightRange, arg4: bigint): Promise<Quote> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuote(arg0, arg1, to_candid_DeliveryType_n53(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_Quote_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuote(arg0, arg1, to_candid_DeliveryType_n53(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_Quote_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByDeliveryType(arg0: DeliveryType): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByDeliveryType(to_candid_DeliveryType_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByDeliveryType(to_candid_DeliveryType_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByDeliveryTypeAndWeightRange(arg0: DeliveryType, arg1: string): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByDeliveryTypeAndWeightRange(to_candid_DeliveryType_n53(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByDeliveryTypeAndWeightRange(to_candid_DeliveryType_n53(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesByWeightRange(arg0: string): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesByWeightRange(arg0);
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesByWeightRange(arg0);
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRouteDistance(arg0: number, arg1: number, arg2: number, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRouteDistance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRouteDistance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getServiceProviderProfile(arg0: Principal): Promise<ServiceProviderProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceProviderProfile(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceProviderProfile(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceProviderProfiles(): Promise<Array<ServiceProviderProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceProviderProfiles();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceProviderProfiles();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightRange(arg0: string): Promise<WeightRange | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightRange(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightRange(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBookingPayment(arg0: string, arg1: string, arg2: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingPayment(arg0, arg1, to_candid_PaymentStatus_n71(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingPayment(arg0, arg1, to_candid_PaymentStatus_n71(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n73(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n73(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n71(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n71(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateServiceProviderProfile(arg0: ServiceProviderProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceProviderProfile(to_candid_ServiceProviderProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceProviderProfile(to_candid_ServiceProviderProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyRazorpayPayment(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRazorpayPayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRazorpayPayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_BookingStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryType): DeliveryType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_InstantQuoteRequest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InstantQuoteRequest): InstantQuoteRequest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MoveType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoveType): MoveType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Quote_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quote): Quote {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceProviderProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceProviderProfile): ServiceProviderProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StripeConfiguration]): StripeConfiguration | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceProviderProfile]): ServiceProviderProfile | null {
    return value.length === 0 ? null : from_candid_ServiceProviderProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WeightRange]): WeightRange | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vehicleType: string;
    dropOffLocation: string;
    addOnServices: Array<string>;
    advanceAmount: bigint;
    schedule: string;
    totalPrice: bigint;
    priceBreakdown: _PriceBreakdown;
    moveType: _MoveType;
    pickupLocation: string;
    advancePercentage: bigint;
}): {
    vehicleType: string;
    dropOffLocation: string;
    addOnServices: Array<string>;
    advanceAmount: bigint;
    schedule: string;
    totalPrice: bigint;
    priceBreakdown: PriceBreakdown;
    moveType: MoveType;
    pickupLocation: string;
    advancePercentage: bigint;
} {
    return {
        vehicleType: value.vehicleType,
        dropOffLocation: value.dropOffLocation,
        addOnServices: value.addOnServices,
        advanceAmount: value.advanceAmount,
        schedule: value.schedule,
        totalPrice: value.totalPrice,
        priceBreakdown: value.priceBreakdown,
        moveType: from_candid_MoveType_n15(_uploadFile, _downloadFile, value.moveType),
        pickupLocation: value.pickupLocation,
        advancePercentage: value.advancePercentage
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    weightRange: _WeightRange;
    dropOffLocation: _Location;
    customer: _Principal;
    estimatedPrice: bigint;
    deliveryType: _DeliveryType;
    distance: bigint;
    advanceAmount: bigint;
    timestamp: _Time;
    pickupLocation: _Location;
    advancePercentage: bigint;
}): {
    id: string;
    weightRange: WeightRange;
    dropOffLocation: Location;
    customer: Principal;
    estimatedPrice: bigint;
    deliveryType: DeliveryType;
    distance: bigint;
    advanceAmount: bigint;
    timestamp: Time;
    pickupLocation: Location;
    advancePercentage: bigint;
} {
    return {
        id: value.id,
        weightRange: value.weightRange,
        dropOffLocation: value.dropOffLocation,
        customer: value.customer,
        estimatedPrice: value.estimatedPrice,
        deliveryType: from_candid_DeliveryType_n21(_uploadFile, _downloadFile, value.deliveryType),
        distance: value.distance,
        advanceAmount: value.advanceAmount,
        timestamp: value.timestamp,
        pickupLocation: value.pickupLocation,
        advancePercentage: value.advancePercentage
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Principal;
    contactInfo: string;
    name: string;
    availability: boolean;
    servicesOffered: Array<_DeliveryType>;
}): {
    id: Principal;
    contactInfo: string;
    name: string;
    availability: boolean;
    servicesOffered: Array<DeliveryType>;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        availability: value.availability,
        servicesOffered: from_candid_vec_n28(_uploadFile, _downloadFile, value.servicesOffered)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: {
        customer: null;
    } | {
        serviceProvider: null;
    };
    contactInfo: string;
    name: string;
}): {
    userType: Variant_customer_serviceProvider;
    contactInfo: string;
    name: string;
} {
    return {
        userType: from_candid_variant_n34(_uploadFile, _downloadFile, value.userType),
        contactInfo: value.contactInfo,
        name: value.name
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    finalPrice: bigint;
    status: _BookingStatus;
    paymentStatus: _PaymentStatus;
    customer: _Principal;
    quoteId: string;
    serviceProvider: _Principal;
    advanceAmount: bigint;
    paymentId: string;
    timestamp: _Time;
    advancePercentage: bigint;
}): {
    id: string;
    finalPrice: bigint;
    status: BookingStatus;
    paymentStatus: PaymentStatus;
    customer: Principal;
    quoteId: string;
    serviceProvider: Principal;
    advanceAmount: bigint;
    paymentId: string;
    timestamp: Time;
    advancePercentage: bigint;
} {
    return {
        id: value.id,
        finalPrice: value.finalPrice,
        status: from_candid_BookingStatus_n7(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_PaymentStatus_n9(_uploadFile, _downloadFile, value.paymentStatus),
        customer: value.customer,
        quoteId: value.quoteId,
        serviceProvider: value.serviceProvider,
        advanceAmount: value.advanceAmount,
        paymentId: value.paymentId,
        timestamp: value.timestamp,
        advancePercentage: value.advancePercentage
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _InstantQuoteRequest]): [string, InstantQuoteRequest] {
    return [
        value[0],
        from_candid_InstantQuoteRequest_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Quote]): [string, Quote] {
    return [
        value[0],
        from_candid_Quote_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Principal, _ServiceProviderProfile]): [Principal, ServiceProviderProfile] {
    return [
        value[0],
        from_candid_ServiceProviderProfile_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Booking]): [string, Booking] {
    return [
        value[0],
        from_candid_Booking_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    driverAssigned: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    confirmed: null;
}): PaymentStatus {
    return "cancelled" in value ? PaymentStatus.cancelled : "driverAssigned" in value ? PaymentStatus.driverAssigned : "completed" in value ? PaymentStatus.completed : "pendingPayment" in value ? PaymentStatus.pendingPayment : "confirmed" in value ? PaymentStatus.confirmed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rk: null;
} | {
    bhk: {
        size: string;
    };
} | {
    office: null;
}): {
    __kind__: "rk";
    rk: null;
} | {
    __kind__: "bhk";
    bhk: {
        size: string;
    };
} | {
    __kind__: "office";
    office: null;
} {
    return "rk" in value ? {
        __kind__: "rk",
        rk: value.rk
    } : "bhk" in value ? {
        __kind__: "bhk",
        bhk: value.bhk
    } : "office" in value ? {
        __kind__: "office",
        office: value.office
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appliance: null;
} | {
    smallPackage: null;
} | {
    furniture: null;
} | {
    mediumPackage: null;
} | {
    largePackage: null;
}): DeliveryType {
    return "appliance" in value ? DeliveryType.appliance : "smallPackage" in value ? DeliveryType.smallPackage : "furniture" in value ? DeliveryType.furniture : "mediumPackage" in value ? DeliveryType.mediumPackage : "largePackage" in value ? DeliveryType.largePackage : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    serviceProvider: null;
}): Variant_customer_serviceProvider {
    return "customer" in value ? Variant_customer_serviceProvider.customer : "serviceProvider" in value ? Variant_customer_serviceProvider.serviceProvider : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n44(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n65(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "pendingPayment" in value ? BookingStatus.pendingPayment : "confirmed" in value ? BookingStatus.confirmed : "inProgress" in value ? BookingStatus.inProgress : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _InstantQuoteRequest]>): Array<[string, InstantQuoteRequest]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Quote]>): Array<[string, Quote]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Principal, _ServiceProviderProfile]>): Array<[Principal, ServiceProviderProfile]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryType>): Array<DeliveryType> {
    return value.map((x)=>from_candid_DeliveryType_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Booking]>): Array<[string, Booking]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InstantQuoteRequest>): Array<InstantQuoteRequest> {
    return value.map((x)=>from_candid_InstantQuoteRequest_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quote>): Array<Quote> {
    return value.map((x)=>from_candid_Quote_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceProviderProfile>): Array<ServiceProviderProfile> {
    return value.map((x)=>from_candid_ServiceProviderProfile_n26(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_DeliveryType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): _DeliveryType {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_MoveType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoveType): _MoveType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceProviderProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceProviderProfile): _ServiceProviderProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [_Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n36(_uploadFile, _downloadFile, value));
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    contactInfo: string;
    name: string;
    availability: boolean;
    servicesOffered: Array<DeliveryType>;
}): {
    id: _Principal;
    contactInfo: string;
    name: string;
    availability: boolean;
    servicesOffered: Array<_DeliveryType>;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        availability: value.availability,
        servicesOffered: to_candid_vec_n52(_uploadFile, _downloadFile, value.servicesOffered)
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: Variant_customer_serviceProvider;
    contactInfo: string;
    name: string;
}): {
    userType: {
        customer: null;
    } | {
        serviceProvider: null;
    };
    contactInfo: string;
    name: string;
} {
    return {
        userType: to_candid_variant_n70(_uploadFile, _downloadFile, value.userType),
        contactInfo: value.contactInfo,
        name: value.name
    };
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "rk";
    rk: null;
} | {
    __kind__: "bhk";
    bhk: {
        size: string;
    };
} | {
    __kind__: "office";
    office: null;
}): {
    rk: null;
} | {
    bhk: {
        size: string;
    };
} | {
    office: null;
} {
    return value.__kind__ === "rk" ? {
        rk: value.rk
    } : value.__kind__ === "bhk" ? {
        bhk: value.bhk
    } : value.__kind__ === "office" ? {
        office: value.office
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): {
    appliance: null;
} | {
    smallPackage: null;
} | {
    furniture: null;
} | {
    mediumPackage: null;
} | {
    largePackage: null;
} {
    return value == DeliveryType.appliance ? {
        appliance: null
    } : value == DeliveryType.smallPackage ? {
        smallPackage: null
    } : value == DeliveryType.furniture ? {
        furniture: null
    } : value == DeliveryType.mediumPackage ? {
        mediumPackage: null
    } : value == DeliveryType.largePackage ? {
        largePackage: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_customer_serviceProvider): {
    customer: null;
} | {
    serviceProvider: null;
} {
    return value == Variant_customer_serviceProvider.customer ? {
        customer: null
    } : value == Variant_customer_serviceProvider.serviceProvider ? {
        serviceProvider: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    cancelled: null;
} | {
    driverAssigned: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    confirmed: null;
} {
    return value == PaymentStatus.cancelled ? {
        cancelled: null
    } : value == PaymentStatus.driverAssigned ? {
        driverAssigned: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.pendingPayment ? {
        pendingPayment: null
    } : value == PaymentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    confirmed: null;
} | {
    inProgress: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.pendingPayment ? {
        pendingPayment: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value == BookingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DeliveryType>): Array<_DeliveryType> {
    return value.map((x)=>to_candid_DeliveryType_n53(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
